### ISSUE TITLE
nucmer_feed.sh doesn't give .delta suffix

### ISSUE THREAD

**Issue by GHJoyce** [dn-ra/RecurM#4]
Issue on Line 36:

`/usr/bin/time nucmer "$CURR_REF" assemblies_iter_built.fa --delta=nucmer_feed_out/"$(date +%d%m%y)"_nucmer_iter_"$ITER" -t 24;`

change to the following:

`
/usr/bin/time nucmer "$CURR_REF" assemblies_iter_built.fa --delta=nucmer_feed_out/"$(date +%d%m%y)"_nucmer_iter_"$ITER" .delta -t 24;
`
in main_pipe.py, it looks for the ".delta" suffix.

**Comment by wwood** [comment]
Hi @GHJoyce this seems like it might be a good fit for a pull request rather than an issue - I can take you through that process tomorrow if you like.
